# Generated by Django 6.0.1 on 2026-01-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'managed': True},
        ),
    ]
