# Generated by Django 6.0.1 on 2026-01-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_teachers_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachers',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='profile_picture_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='verification_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
