# Generated by Django 6.0.1 on 2026-01-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_groupstudents_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
